// <auto-generated />
using System;
using AutoDocService.DL.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoDocService.Migrations
{
    [DbContext(typeof(ContractGenerationContext))]
    partial class ContractGenerationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("AutoDocService.DL.Entities.DocumentTemplates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DateInsert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateVerified")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserInsert")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserUpdate")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserVerified")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdTemplate", "Version" }, "UC_DocumentTemplate")
                        .IsUnique();

                    b.ToTable("DocumentTemplate", "dbo");
                });

            modelBuilder.Entity("AutoDocService.DL.Entities.SectionGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateInserted")
                        .HasColumnType("datetime")
                        .HasColumnName("DateInserted");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime")
                        .HasColumnName("DateUpdated");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("Status");

                    b.Property<string>("UserInserted")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("UserInserted");

                    b.Property<string>("UserUpdated")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("UserUpdated");

                    b.HasKey("ID");

                    b.ToTable("SectionGroup", "dbo");
                });

            modelBuilder.Entity("AutoDocService.DL.Entities.Sections", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateInsert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSection")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserInsert")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserUpdate")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdSection", "Version" }, "UC_Sections")
                        .IsUnique();

                    b.ToTable("Sections", "dbo");
                });

            modelBuilder.Entity("AutoDocService.DL.Entities.TemplateSectionsRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdSection")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PageBreak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemplateVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdSection", "SectionVersion");

                    b.HasIndex("IdTemplate", "TemplateVersion");

                    b.ToTable("TemplateSectionsRelation", "dbo");
                });

            modelBuilder.Entity("AutoDocService.DL.Entities.TemplateSectionsRelation", b =>
                {
                    b.HasOne("AutoDocService.DL.Entities.Sections", "Section")
                        .WithMany("TemplateSectionsRelations")
                        .HasForeignKey("IdSection", "SectionVersion")
                        .HasPrincipalKey("IdSection", "Version")
                        .IsRequired()
                        .HasConstraintName("FK__TemplateSections__7DD962F1");

                    b.HasOne("AutoDocService.DL.Entities.DocumentTemplates", "DocumentTemplate")
                        .WithMany("TemplateSectionsRelations")
                        .HasForeignKey("IdTemplate", "TemplateVersion")
                        .HasPrincipalKey("IdTemplate", "Version")
                        .IsRequired()
                        .HasConstraintName("FK__TemplateSections__7CE53EB8");

                    b.Navigation("DocumentTemplate");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("AutoDocService.DL.Entities.DocumentTemplates", b =>
                {
                    b.Navigation("TemplateSectionsRelations");
                });

            modelBuilder.Entity("AutoDocService.DL.Entities.Sections", b =>
                {
                    b.Navigation("TemplateSectionsRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
